server:
  port: 9094
spring:
  application:
    name: report-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
resilience4j.retry:
  instances:
    default:
      maxAttempts: 3
      waitDuration: 5s
      enableExponentialBackoff: true
resilience4j.circuitbreaker:
  instances:
    default:
      minimumNumberOfCalls: 25
resilience4j.ratelimiter:
  instances:
    default:
      limitForPeriod: 4
      limitRefreshPeriod: 10s
resilience4j.timelimiter:
  instances:
    default:
      timeoutDuration: 2s
billing:
  app: This is billing App Reporting Service defaulttest
